-- 043_create_scholarships.sql
-- 장학금 관리 테이블 생성 및 pgcrypto를 활용한 암호화 처리

-- 1. Table 생성
CREATE TABLE IF NOT EXISTS public.scholarships (
  id bigint generated by default as identity primary key,
  year integer,
  dept text,
  major text,
  course text,
  student_id text,
  name text,
  resident_id bytea,
  grade text,
  enroll_status text,
  reg_status text,
  amount text,
  bank_name text,
  account_num bytea,
  account_holder text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. 프론트엔드 연동을 위한 Updatable View 생성
CREATE OR REPLACE VIEW public.scholarships_view AS
SELECT
  id,
  year,
  dept,
  major,
  course,
  student_id,
  name,
  pgp_sym_decrypt(resident_id, 'anchor_secure_key_2026') AS resident_id,
  grade,
  enroll_status,
  reg_status,
  amount,
  bank_name,
  pgp_sym_decrypt(account_num, 'anchor_secure_key_2026') AS account_num,
  account_holder,
  created_at,
  updated_at
FROM public.scholarships;

-- 3. View 갱신을 위한 INSTEAD OF Trigger 함수
CREATE OR REPLACE FUNCTION public.scholarships_view_mutate()
RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.scholarships (
      year, dept, major, course, student_id, name,
      resident_id, grade, enroll_status, reg_status, amount, bank_name,
      account_num, account_holder, created_at, updated_at
    ) VALUES (
      NEW.year, NEW.dept, NEW.major, NEW.course, NEW.student_id, NEW.name,
      CASE WHEN NEW.resident_id IS NOT NULL AND NEW.resident_id <> '' THEN pgp_sym_encrypt(NEW.resident_id, 'anchor_secure_key_2026') ELSE NULL END,
      NEW.grade, NEW.enroll_status, NEW.reg_status, NEW.amount, NEW.bank_name,
      CASE WHEN NEW.account_num IS NOT NULL AND NEW.account_num <> '' THEN pgp_sym_encrypt(NEW.account_num, 'anchor_secure_key_2026') ELSE NULL END,
      NEW.account_holder, COALESCE(NEW.created_at, now()), COALESCE(NEW.updated_at, now())
    ) RETURNING id, created_at, updated_at INTO NEW.id, NEW.created_at, NEW.updated_at;
    RETURN NEW;
  ELSIF TG_OP = 'UPDATE' THEN
    UPDATE public.scholarships
    SET
      year = NEW.year,
      dept = NEW.dept,
      major = NEW.major,
      course = NEW.course,
      student_id = NEW.student_id,
      name = NEW.name,
      resident_id = CASE WHEN NEW.resident_id IS NOT NULL AND NEW.resident_id <> '' THEN pgp_sym_encrypt(NEW.resident_id, 'anchor_secure_key_2026') ELSE NULL END,
      grade = NEW.grade,
      enroll_status = NEW.enroll_status,
      reg_status = NEW.reg_status,
      amount = NEW.amount,
      bank_name = NEW.bank_name,
      account_num = CASE WHEN NEW.account_num IS NOT NULL AND NEW.account_num <> '' THEN pgp_sym_encrypt(NEW.account_num, 'anchor_secure_key_2026') ELSE NULL END,
      account_holder = NEW.account_holder,
      updated_at = now()
    WHERE id = OLD.id
    RETURNING updated_at INTO NEW.updated_at;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    DELETE FROM public.scholarships WHERE id = OLD.id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Trigger 부착
DROP TRIGGER IF EXISTS scholarships_view_trigger ON public.scholarships_view;
CREATE TRIGGER scholarships_view_trigger
INSTEAD OF INSERT OR UPDATE OR DELETE ON public.scholarships_view
FOR EACH ROW EXECUTE FUNCTION public.scholarships_view_mutate();

-- 5. 권한 및 RLS 정책
ALTER TABLE public.scholarships ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for authenticated users on scholarships" ON public.scholarships;
CREATE POLICY "Enable read access for authenticated users on scholarships"
  ON public.scholarships FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "Enable all access for authenticated users on scholarships" ON public.scholarships;
CREATE POLICY "Enable all access for authenticated users on scholarships"
  ON public.scholarships FOR ALL
  TO authenticated USING (true) WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.scholarships TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.scholarships_view TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.scholarships_view TO anon;
