-- supabase/migrations/074_create_equipment_assets_table.sql
-- 7번 규칙(Supabase 쿼리 관리)에 따라 순서 번호를 붙여서 작성합니다.
-- 기자재 자산 관리를 위해 equipment_assets 테이블을 생성하고,
-- 기존 procurement_equipment 테이블에 바코드 및 자산 관리번호 컬럼을 추가합니다.

-- 1) 기자재 자산 관리용 테이블 생성
CREATE TABLE IF NOT EXISTS public.equipment_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode_id VARCHAR(255) UNIQUE NOT NULL,
    asset_number VARCHAR(255) NOT NULL,
    item_name VARCHAR(255) NOT NULL,
    dept_name VARCHAR(255) DEFAULT '',
    unit_price BIGINT DEFAULT 0,
    quantity INTEGER DEFAULT 1,
    stock_location VARCHAR(255) DEFAULT '',
    category VARCHAR(50) DEFAULT 'ai_dx',
    usage_type VARCHAR(50) DEFAULT '정규교과',
    memo TEXT DEFAULT '',
    last_checked_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMENT ON TABLE public.equipment_assets IS '자산 관리용 기자재 현황 대장';
COMMENT ON COLUMN public.equipment_assets.barcode_id IS '기자재 바코드 정보 (고유 식별자)';
COMMENT ON COLUMN public.equipment_assets.asset_number IS '기자재 관리번호';
COMMENT ON COLUMN public.equipment_assets.last_checked_at IS '바코드 스캐너를 통한 마지막 실시간 점검 시각';

-- 2) 조달관리 핵심 기자재 테이블(procurement_equipment)에 바코드 및 관리번호 필드 확장
ALTER TABLE public.procurement_equipment ADD COLUMN IF NOT EXISTS barcode TEXT DEFAULT '';
ALTER TABLE public.procurement_equipment ADD COLUMN IF NOT EXISTS asset_number TEXT DEFAULT '';

-- RLS 활성화 및 익명/인증 사용자 무제한 통과 권한 정책 부여
ALTER TABLE public.equipment_assets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read/write access for all on equipment_assets" ON public.equipment_assets;
CREATE POLICY "Allow read/write access for all on equipment_assets"
ON public.equipment_assets
FOR ALL
TO public
USING (true)
WITH CHECK (true);
