-- Supabase Auth is the authentication authority; rise_users stores authorization/profile data only.

CREATE TABLE IF NOT EXISTS public.rise_user_auth_migration_issues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_type TEXT NOT NULL,
  rise_user_id TEXT,
  rise_user_uuid UUID,
  email TEXT,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  detected_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

TRUNCATE TABLE public.rise_user_auth_migration_issues;

INSERT INTO public.rise_user_auth_migration_issues (
  issue_type, rise_user_id, email, details
)
SELECT
  'DUPLICATE_NORMALIZED_EMAIL',
  min(u.id),
  lower(trim(u.email)),
  jsonb_build_object('rise_user_ids', jsonb_agg(u.id ORDER BY u.id))
FROM public.rise_users u
WHERE nullif(trim(u.email), '') IS NOT NULL
GROUP BY lower(trim(u.email))
HAVING count(*) > 1;

INSERT INTO public.rise_user_auth_migration_issues (
  issue_type, rise_user_id, rise_user_uuid, email, details
)
SELECT
  'UUID_EMAIL_MISMATCH',
  u.id,
  u.uuid,
  u.email,
  jsonb_build_object('auth_email', a.email)
FROM public.rise_users u
JOIN auth.users a ON a.id = u.uuid
WHERE nullif(trim(u.email), '') IS NOT NULL
  AND lower(trim(u.email)) <> lower(trim(a.email));

INSERT INTO public.rise_user_auth_migration_issues (
  issue_type, rise_user_id, rise_user_uuid, email
)
SELECT 'ORPHAN_AUTH_UUID', u.id, u.uuid, u.email
FROM public.rise_users u
LEFT JOIN auth.users a ON a.id = u.uuid
WHERE u.uuid IS NOT NULL AND a.id IS NULL;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.rise_user_auth_migration_issues
    WHERE issue_type IN (
      'DUPLICATE_NORMALIZED_EMAIL',
      'UUID_EMAIL_MISMATCH',
      'ORPHAN_AUTH_UUID'
    )
  ) THEN
    RAISE EXCEPTION
      'rise_users Auth migration preflight failed; inspect rise_user_auth_migration_issues';
  END IF;
END;
$$;

UPDATE public.rise_users
SET email = lower(trim(email))
WHERE email IS DISTINCT FROM lower(trim(email));

UPDATE public.rise_users u
SET uuid = a.id
FROM auth.users a
WHERE u.uuid IS NULL
  AND nullif(trim(u.email), '') IS NOT NULL
  AND lower(trim(a.email)) = lower(trim(u.email));

INSERT INTO public.rise_user_auth_migration_issues (
  issue_type, rise_user_id, email,
  details
)
SELECT
  'MISSING_AUTH_IDENTITY',
  u.id,
  u.email,
  jsonb_build_object('login_enabled', false)
FROM public.rise_users u
WHERE u.uuid IS NULL;

ALTER TABLE public.rise_users
  ALTER COLUMN pw DROP NOT NULL;

UPDATE public.rise_users
SET pw = NULL
WHERE pw IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS rise_users_email_lower_unique
  ON public.rise_users (lower(email))
  WHERE email IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS rise_users_uuid_unique
  ON public.rise_users (uuid)
  WHERE uuid IS NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'rise_users_uuid_auth_users_fk'
      AND conrelid = 'public.rise_users'::regclass
  ) THEN
    ALTER TABLE public.rise_users
      ADD CONSTRAINT rise_users_uuid_auth_users_fk
      FOREIGN KEY (uuid) REFERENCES auth.users(id)
      ON UPDATE CASCADE ON DELETE RESTRICT;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.enforce_rise_user_auth_identity()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  auth_email TEXT;
BEGIN
  IF NEW.uuid IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT lower(trim(a.email))
  INTO auth_email
  FROM auth.users a
  WHERE a.id = NEW.uuid;

  IF auth_email IS NULL THEN
    RAISE EXCEPTION 'AUTH_IDENTITY_NOT_FOUND';
  END IF;

  IF nullif(trim(NEW.email), '') IS NULL THEN
    NEW.email := auth_email;
  ELSIF lower(trim(NEW.email)) <> auth_email THEN
    RAISE EXCEPTION 'AUTH_EMAIL_MISMATCH';
  ELSE
    NEW.email := auth_email;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS rise_users_auth_identity_guard ON public.rise_users;
CREATE TRIGGER rise_users_auth_identity_guard
BEFORE INSERT OR UPDATE OF uuid, email ON public.rise_users
FOR EACH ROW EXECUTE FUNCTION public.enforce_rise_user_auth_identity();

REVOKE ALL ON FUNCTION public.enforce_rise_user_auth_identity() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.is_rise_users_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.rise_users u
    WHERE u.uuid = auth.uid()
      AND u.approved = true
      AND u.role_key IN (
        'ADMIN', 'DIRECTOR', 'G_DIRECTOR', 'HQ_HEAD', 'TEAM_LEADER', 'MANAGER'
      )
  );
$$;

REVOKE ALL ON FUNCTION public.is_rise_users_admin() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_rise_users_admin() TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.get_current_rise_user()
RETURNS TABLE (
  id TEXT,
  name TEXT,
  role_key TEXT,
  approved BOOLEAN,
  uuid UUID,
  email TEXT
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT u.id, u.name, u.role_key, u.approved, u.uuid, u.email
  FROM public.rise_users u
  WHERE u.uuid = auth.uid()
  LIMIT 1;
$$;

REVOKE ALL ON FUNCTION public.get_current_rise_user() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_current_rise_user() TO authenticated, service_role;

DO $$
DECLARE
  policy_row RECORD;
BEGIN
  FOR policy_row IN
    SELECT policyname
    FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'rise_users'
  LOOP
    EXECUTE format(
      'DROP POLICY IF EXISTS %I ON public.rise_users',
      policy_row.policyname
    );
  END LOOP;
END;
$$;

ALTER TABLE public.rise_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY rise_users_select_self
  ON public.rise_users
  FOR SELECT TO authenticated
  USING (uuid = auth.uid());

CREATE POLICY rise_users_admin_select
  ON public.rise_users
  FOR SELECT TO authenticated
  USING (public.is_rise_users_admin());

CREATE POLICY rise_users_admin_insert
  ON public.rise_users
  FOR INSERT TO authenticated
  WITH CHECK (public.is_rise_users_admin());

CREATE POLICY rise_users_admin_update
  ON public.rise_users
  FOR UPDATE TO authenticated
  USING (public.is_rise_users_admin())
  WITH CHECK (public.is_rise_users_admin());

CREATE POLICY rise_users_admin_delete
  ON public.rise_users
  FOR DELETE TO authenticated
  USING (public.is_rise_users_admin());

REVOKE ALL ON TABLE public.rise_users FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.rise_users TO authenticated;
GRANT ALL ON TABLE public.rise_users TO service_role;

ALTER TABLE public.rise_user_auth_migration_issues ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.rise_user_auth_migration_issues FROM anon, authenticated;
GRANT ALL ON TABLE public.rise_user_auth_migration_issues TO service_role;

COMMENT ON COLUMN public.rise_users.pw IS
  'Deprecated. Authentication secrets are stored and verified only by Supabase Auth.';
COMMENT ON COLUMN public.rise_users.uuid IS
  'Canonical identity link to auth.users.id; authorization policies compare this value with auth.uid().';
